# Generated by Django 6.0.1 on 2026-02-13 21:23

import core.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField(unique=True)),
                ('actual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_largo', models.CharField(max_length=100)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('admin', 'Administrador')], db_column='rol', default='user', max_length=20)),
                ('nombre_completo', models.CharField(blank=True, db_column='nombre', max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PartidoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato_presidencial', models.CharField(blank=True, max_length=100, null=True)),
                ('lider_partido', models.CharField(blank=True, max_length=100, null=True)),
                ('color_primario', models.CharField(default='#000000', max_length=7)),
                ('logo_key', models.CharField(max_length=50)),
                ('candidato_key', models.CharField(default='DEFAULT_CANDIDATE', max_length=50)),
                ('anio_fundacion', models.IntegerField(blank=True, null=True)),
                ('tipo_organizacion', models.CharField(default='Partido Político', max_length=50)),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('presidente', 'Presidente'), ('1er vicepresidente', '1er Vicepresidente'), ('2do vicepresidente', '2do Vicepresidente'), ('diputado', 'Diputado'), ('senador nacional', 'Senador Nacional'), ('senador regional', 'Senador Regional'), ('parlamento andino', 'Parlamento Andino')], max_length=50)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('region_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.URLField(blank=True, max_length=500, null=True)),
                ('hojavida', models.URLField(blank=True, max_length=500, null=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='core.partido')),
                ('region_rel', models.ForeignKey(db_column='id_region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
            ],
        ),
    ]
