# Generated by Django 6.0.1 on 2026-02-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_managers_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidometadata',
            name='logo_key',
        ),
        migrations.AddField(
            model_name='partidometadata',
            name='plan_gobierno',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
