# Generated by Django 6.0.1 on 2026-01-26 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoPosicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posicion_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('posicion_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eleccion')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('estado', models.CharField(default='activa', max_length=20)),
                ('eje', models.CharField(max_length=1)),
                ('direccion', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='core.eleccion')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fuente', models.URLField(blank=True, max_length=500, null=True)),
                ('valor', models.IntegerField()),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eleccion')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partido')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cod_sesion', models.CharField(editable=False, max_length=20, unique=True)),
                ('estado', models.CharField(default='en_progreso', max_length=20)),
                ('resultado_x', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('resultado_y', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pregunta')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='quiz.usuariosesion')),
            ],
        ),
    ]
