# Generated by Django 6.0.1 on 2026-02-13 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_x', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('posicion_y', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partido')),
            ],
            options={
                'db_table': 'partidoposicioncache',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('eje', models.CharField(choices=[('X', 'Económico'), ('Y', 'Social')], max_length=1)),
                ('direccion', models.IntegerField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='core.eleccion')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('fuente', models.CharField(blank=True, max_length=500, null=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partido')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(editable=False, max_length=10, unique=True)),
                ('resultado_x', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('resultado_y', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('eleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eleccion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pregunta')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='quiz.usuariosesion')),
            ],
        ),
    ]
